### ISSUE TITLE
Slider doesn't work on second tab

### ISSUE THREAD

**Issue by ma261065** [SergiuToporjinschi/node-red-contrib-heater-controller#50] opened 2020-03-30 11:56 UTC
If I put this control on any tab other than the default (first) tab, then when I slide the slider the UI jumps back to the first tab.

I then have to click the hamburger menu and go back to the tab where the control is actually displayed.

**Comment by SergiuToporjinschi** [comment] 2020-03-30 12:34
this is duplicate of #37

**Closed by SergiuToporjinschi** 2020-03-30 12:34 UTC
