### ISSUE TITLE
Changeable Calendar by message

### ISSUE THREAD

**Issue by WoMec** [SergiuToporjinschi/node-red-contrib-heater-controller#16] opened 2019-01-27 16:07 UTC
Hi, I'm trying to setup home thermostat, but no luck so far. When I deploy your node, setup dashboard group and deploy flow, I can't see ui in dashbard, I get error to debug tab

```
27. 1. 2019 16:57:14  node: heater
msg : error
"TypeError: Cannot read property 'push' of undefined"
```

and syslog says

```
Jan 27 16:57:09 emonpi Node-RED[32323]: { Error: Cannot find module 'node-red-dashboard'
Jan 27 16:57:09 emonpi Node-RED[32323]:     at Object.requireModule [as require] (/usr/lib/node_modules/node-red/red/runtime/nodes/registry/loader.js:71:19)
Jan 27 16:57:09 emonpi Node-RED[32323]:     at new getNode (/home/pi/.node-red/node_modules/node-red-contrib-heater-controller/heater-controller.js:8:26)
Jan 27 16:57:09 emonpi Node-RED[32323]:     at createNode (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:305:18)
Jan 27 16:57:09 emonpi Node-RED[32323]:     at Flow.start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:89:35)
Jan 27 16:57:09 emonpi Node-RED[32323]:     at start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:328:29)
Jan 27 16:57:09 emonpi Node-RED[32323]:     at /usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:164:25
Jan 27 16:57:09 emonpi Node-RED[32323]:     at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
Jan 27 16:57:09 emonpi Node-RED[32323]: 27 Jan 16:57:09 - [error] [ui_heater_controller:b78f2f56.b8b6f] TypeError: Cannot read property 'push' of undefined
```

**node red version: v0.19.5
dashboard version: 2.13.0
thermostat verstion: 1.2.0**

I also tried to add some dummy buttons and other stuff to dashboard and those are displayed correctly

**Comment by SergiuToporjinschi** [comment] 2019-01-28 11:57
Hmmm that's trange, at that line is getting a reference to dashboard. It's like not having node-red-dashboard module installed; 
I have 2.12.1 probably it has some major change in 13. I will update and do the change tonight.

**Comment by SergiuToporjinschi** [comment] 2019-01-28 22:53
Hi, I looked on this but unfortunately I could not reproduce it; Now I'm using 
node-red-dashboard: 2.13.1 -> unfortunately I cannot put 2.13.0 
node red version: 0.19.5

Can you please update dashboard to 2.13.1 ? maybe they had an issue at 2.13.0. And let me know if it's working

**Comment by WoMec** [comment] 2019-01-29 07:47
I found probable problem. I found, that months ago I installed dashboard via cli so I was unable to update dashboard module via palette manager. So I uninstalled dashboard from cli, reinstall it from palette manager and heater control works perfectly now.  

Maybe I have one more question. is it somehow possible to edit calendar from UI?  Via some other input? Or do you planning to add calendar editor to the UI?

**Comment by SergiuToporjinschi** [comment] 2019-01-29 08:20
Good to hear that is working. 
No I did not planned this, but it seems a good idea. The problem is that I don't know when I will be able to do that. Currently I'm working on other project

**Comment by vdoucet** [comment] 2019-01-29 08:35
I thought of using google calendar as an input to userTargetValue but I'm not ready yet to test that.
That way you can update your calendar from anywhere ... not sure yet how to run it though !

**Comment by SergiuToporjinschi** [comment] 2019-01-29 08:43
I've marked this as enhancement. I will do the changes for that.

**Comment by WoMec** [comment] 2019-02-01 17:14
Changeable Calendar by message or UI in widget :)

**Comment by ulfh2018** [comment] 2019-02-28 17:36
Would love to have that functionality. Just what I need for my project!
Good luck - this node looks greate!

**Comment by daimoniac** [comment] 2019-03-02 05:42
I think that pushing in the calendar would be a great addition. At the moment, you cannot really use this widget in a subflow because of that restriction.

**Comment by ulfh2018** [comment] 2019-03-02 08:07
Yes, but I hope that the calendar will be accessible from the desktop, and not via Google Calendar, since there are a lot of people that doe's not us it. I think it would be enough to have access to a general week that is not associated with any particular week in the year.
I have started making an application to control heating at my son's apartment. The electricity in Norway is very expencive for the time beeing, though compared to many other places in the world it's relative cheap.

**Comment by WoMec** [comment] 2019-03-02 16:58
It would be nice to have something like this (Wolf Smartset app)

![image](https://user-images.githubusercontent.com/7909801/53684965-8619f880-3d14-11e9-82dc-82407b7b7162.png)

**Comment by SergiuToporjinschi** [comment] 2019-03-02 21:32
@WoMec  looks nice, but is not sow easy to do.. let's not forget that there are a lot of restriction, basically I have done a plugin to an app ... probably there will be a lot of restrictions. 
And in your picture I cannot see how the intervals can be added and set the temperature for each interval. 
some sliders are already in angular material 
https://material.angularjs.org/latest/demo/slider 
but those does not permit multiple intervals 
currently I'm stacked in an firmware update for my IOT devices...

**Comment by ulfh2018** [comment] 2019-03-03 07:04
Would it be possible to add an input parameter that could change the calendar json? Then I can do the rest myself

**Comment by SergiuToporjinschi** [comment] 2019-03-03 20:22
@ulfh2018 if you implement it, and create a pull request, I would review it and merge it

**Comment by ulfh2018** [comment] 2019-03-04 13:34
Sergiu – I'm sorry but I'm not a programmer, so I was thinking about trying to use standard Nod-Red plugins to get information I can format to a jason string, but then I need an input parameter to your node that will be able to change the values in the json string you are using. Don't even know if this is possible to implement.

 

Best regards

 

Ulf

 

Fra: Sergiu Toporjinschi [mailto:notifications@github.com] 
Sendt: 3. mars 2019 21:23
Til: SergiuToporjinschi/node-red-contrib-heater-controller
Kopi: ulfh2018; Mention
Emne: Re: [SergiuToporjinschi/node-red-contrib-heater-controller] Changeable Calendar by message (#16)

 

@ulfh2018 <https://github.com/ulfh2018>  if you implement it, and create a pull request, I would review it and merge it

**Comment by SergiuToporjinschi** [comment] 2019-03-05 16:58
@ulfh2018 I understand, I will do the change, is possible, but you have to wait.
Thank you for understanding!

**Comment by SergiuToporjinschi** [comment] 2019-03-13 21:32
Check latest version and let me know how is working

**Closed by SergiuToporjinschi** 2019-03-13 21:32 UTC
Labels: enhancement

**Comment by ulfh2018** [comment] 2019-03-14 16:20
Hi.
Downloaded latest version, which looks nice. I have downloaded the test flow, and there might be things I don't understand, but when I try to change the calendar values (for example Monday 00:00 which have a value of 99, I cannot see that anything changes.

Best regards
Ulf

**Comment by ulfh2018** [comment] 2019-03-14 16:32
I have just upgraded to 1.0.2

Sendt fra min iPhone

**Comment by SergiuToporjinschi** [comment] 2019-03-14 16:55
@ulfh2018 the latest version is 1.2.1 
you need to send a message with topic  ```setCalendar``` and needs to be JSON type not String representing a json 
![image](https://user-images.githubusercontent.com/9376439/54375978-ba81a300-468a-11e9-89f8-445d149e424c.png)

**Comment by ulfh2018** [comment] 2019-03-14 18:38
Does this mean that your example does not work? I copied the code, then I sent Current temp, which worked, so I sent setCalendar, and that did not change anything in the calendar. Monday was still set up with 99 degrees at 00:00. I used your sample code, not anything I had written myself

 

Fra: Sergiu Toporjinschi [mailto:notifications@github.com] 
Sendt: 14. mars 2019 17:56
Til: SergiuToporjinschi/node-red-contrib-heater-controller
Kopi: ulfh2018; Mention
Emne: Re: [SergiuToporjinschi/node-red-contrib-heater-controller] Changeable Calendar by message (#16)

 

@ulfh2018 <https://github.com/ulfh2018>  the latest version is 1.2.1
you need to send a message with topic setCalendar and needs to be JSON type not String representing a json
 <https://user-images.githubusercontent.com/9376439/54375978-ba81a300-468a-11e9-89f8-445d149e424c.png> image

**Comment by SergiuToporjinschi** [comment] 2019-03-14 18:41
@ulfh2018 Are you using 1.2.1 version?

**Comment by ulfh2018** [comment] 2019-03-14 18:42
Yes, I am

 

 

Fra: Sergiu Toporjinschi [mailto:notifications@github.com] 
Sendt: 14. mars 2019 19:42
Til: SergiuToporjinschi/node-red-contrib-heater-controller
Kopi: ulfh2018; Mention
Emne: Re: [SergiuToporjinschi/node-red-contrib-heater-controller] Changeable Calendar by message (#16)

 

@ulfh2018 <https://github.com/ulfh2018>  Are you using 1.2.1 version?

**Comment by benbamm** [comment] 2020-11-14 18:51
Is there any news on this? I have also been trying to change the calendar through injecting JSON but I also can not get it to work...

**Comment by andreapx** [comment] 2023-04-10 15:41
@SergiuToporjinschi maybe you could use the output of the node [node-red-contrib-ui-time-scheduler](https://flows.nodered.org/node/node-red-contrib-ui-time-scheduler/in/590bc13ff3a5f005c7d2189bbb563976) to feed the data into your node
